import type { NextPage } from 'next'
import Head from 'next/head'
import { Error404 } from '../components/404'
import { FormInput } from '../components/FormInput'
import { Header } from '../layout/Header'
import { Primary, Silver, WrapOverflowssss } from '../stories/Button.stories'
import { Default, Secondary } from '../stories/Button2.stories'
import { MyFormInput } from '../stories/FormInput.stories'
import { WrapOverflow } from '../stories/Stack.stories'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
        <FormInput label='inputBase' />
        <MyFormInput />
      {/* <div className='Rectangle'> */}
        {/* <p className='My-Strange-button-Stroke' >my strange stroke</p> */}
      {/* </div> */}
    </div>
  )
}

export default Home
